Document: manual-firewall
Title: Debian manual-firewall Manual
Author: <insert document author here>
Abstract: This manual describes what manual-firewall is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/manual-firewall/manual-firewall.sgml.gz

Format: postscript
Files: /usr/share/doc/manual-firewall/manual-firewall.ps.gz

Format: text
Files: /usr/share/doc/manual-firewall/manual-firewall.text.gz

Format: HTML
Index: /usr/share/doc/manual-firewall/html/index.html
Files: /usr/share/doc/manual-firewall/html/*.html
